@port = 5014
# Register default user
POST http://localhost:{{port}}/auth/register
Content-Type: application/json

{
    "email":"szymon@gmail.com",
    "password": "szymon"
    # if there is no 'type' field user is 'default'
}
###

# Login non-owner user
POST http://localhost:{{port}}/auth/login
Content-Type: application/json

{
    "email":"szymon@gmail.com",
    "password": "szymon"
}
###

# Register NON-default user
POST http://localhost:{{port}}/auth/register
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password": "admin",
    "type": "admin"
}
###

# Login ADMIN
POST http://localhost:{{port}}/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password": "admin"
}