@port = 5014
@token = eyJhbGciOiJIUzI1NiJ9.NjM3MTJiNmY1ZTgyNGM5NjkxNjZhY2E4.gZ9xiKnsaU4e9fCRkJ-pAZ-X5OSCylYChs__wk8xS0U
@non-owener-token = eyJhbGciOiJIUzI1NiJ9.NjM3MTJhZDc1ZTgyNGM5NjkxNjZhY2Ey.RWwMaSZhNit3HsjNapKmkvEw8QsmdtdjBI6_Hrp8oNo

# Get all shops
GET http://localhost:{{port}}/shop/
###
# Get shop by ID
GET http://localhost:{{port}}/shop/637135977fd81f0c3b1bb79d
###
#Add shop
POST http://localhost:{{port}}/shop/add
Content-Type: application/json
token: {{token}}

{

	"name": "RewakShop45",
	"address": {
		"city": "Legnica",
        "street": "Jezierzana",
		"number": "14"
	},
	"flavors": ["vanilla", "blueberry", "strawberry", "cherry"],
	"openHours": [
		["1:30", "17:40"],
		["2:30", "13:30"],
		["3:40", "14:40"],
        ["4:30", "16:40"],
        ["5:40", "17:40"],
        ["6:40", "17:40"],
        ["7:40", "17:40"]
	]
}
###

#Delete shop
DELETE http://localhost:{{port}}/shop/delete/63712f618acf1f7766834df5
Content-Type: application/json
token: {{token}}

###

#Delete shop by non-owner
DELETE http://localhost:{{port}}/shop/delete/63712b925e824c969166acac
Content-Type: application/json
token: {{non-owener-token}}
###

# Update shop
PUT http://localhost:{{port}}/shop/update/637135977fd81f0c3b1bb79d
Content-Type: application/json
token: {{token}}

{
	"name": "AfterUpdate Rewak Shop"
}